export const testCategoriesProducts = [
  { id: 1, name: "Фрукти" },
  { id: 2, name: "Овочі" },
  { id: 3, name: "М'ясо" },
  { id: 4, name: "Молочні продукти" },
  { id: 5, name: "Зернові" },
];

export const testProducts = [
  {
    id: 1,
    name: "Яблуко зелене",
    calories: 52,
    protein: 0.3,
    fat: 0.2,
    carbs: 14,
    img: "/images/zelenoe-abloko-izolirovannoe-na-belizne.jpg",
    categoryId: 1,
  },
  {
    id: 2,
    name: "Банан",
    calories: 96,
    protein: 1.3,
    fat: 0.3,
    carbs: 27,
    img: "/images/banany-na-belom-fone.jpg",
    categoryId: 1,
  },
  {
    id: 3,
    name: "Куряче філе смажене",
    calories: 179,
    protein: 29,
    fat: 6.9,
    carbs: 0.6,
    img: "/images/kurinaa-grudka-so-svezim-salatom-rukkoloi-i-pomidorami.jpg",
    categoryId: 3,
  },
  {
    id: 4,
    name: "Броколі",
    calories: 55,
    protein: 3.7,
    fat: 0.6,
    carbs: 11,
    img: "/images/poleznaa-brokkoli-vid-speredi.jpg",
    categoryId: 2,
  },
  {
    id: 5,
    name: "Рис варений на воді",
    calories: 117,
    protein: 2.9,
    fat: 0.4,
    carbs: 25.2,
    img: "/images/vid-sverhu-vkusnyi-otvarnoi-ris-s-syrym-risom-vnutri-malen-koi-tarelki-na-temnom-stole.jpg",
    categoryId: 5,
  },
];
